services:
  - type: web
    name: stock-market-app
    runtime: docker
    region: singapore
    plan: starter
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        scope: run
        value: ${MYSQL_HOST}
      - key: DB_USER
        scope: run
        value: ${MYSQL_USER}
      - key: DB_PASS
        scope: run
        value: ${MYSQL_PASSWORD}
      - key: DB_NAME
        scope: run
        value: ${MYSQL_DATABASE}
      - key: DB_PORT
        scope: run
        value: "3306"
