services:
  - type: web
    name: indian-stock-market-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/indices
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
